import fs from "node:fs"
import type { Series } from "../model/series.ts"
import type { Vault } from "./vault.ts"

export const PREAMBLE_FILE = "preamble.sty"

/**
 * Obsidian's Extended MathJax plugin reads one preamble for the whole vault, while macros
 * belong to books. The preamble is the union; a name two books define differently keeps
 * the first definition, so previews of the other book may differ from its website.
 */
export class ObsidianPreamble {
  constructor(private readonly series: Series) {}

  text(): { text: string; conflicts: string[] } {
    const chosen = new Map<string, { line: string; book: string }>()
    const conflicts: string[] = []
    for (const book of this.series.books) {
      for (const [name, line] of book.macros.lines()) {
        const earlier = chosen.get(name)
        if (!earlier) chosen.set(name, { line, book: book.slug })
        else if (earlier.line !== line) {
          conflicts.push(
            `\\${name} differs between ${earlier.book} and ${book.slug}; the preview uses ${earlier.book}'s`,
          )
        }
      }
    }
    const header = "% Generated by `npm run preamble` from every book.md. Edit the books, not this file.\n"
    return { text: header + [...chosen.values()].map(({ line }) => line).join("\n") + "\n", conflicts }
  }

  write(vault: Vault): { file: string; conflicts: string[] } {
    const { text, conflicts } = this.text()
    const file = vault.absolute(PREAMBLE_FILE)
    fs.writeFileSync(file, text, "utf8")
    return { file, conflicts }
  }
}
