import assert from "node:assert/strict"
import fs from "node:fs"
import test from "node:test"
import { ObsidianPreamble } from "../../publish/obsidian/preamble.ts"
import { BOOK_MD, makeVault, readSeries, SERIES_MD } from "../support/fixture.ts"

test("the Obsidian preamble is the union of every book's macros", () => {
  const beta = BOOK_MD.replace(
    "\\newcommand{\\R}{\\mathbb{R}}",
    "\\newcommand{\\R}{\\mathbf{R}}\n  \\newcommand{\\E}{\\mathbb{E}}",
  )
  const root = makeVault({
    "series.md": SERIES_MD.replace("books: [alpha]", "books: [alpha, beta]"),
    "beta/book.md": beta,
    "beta/cover.svg": "<svg/>",
    "beta/zh/01-一.md": "# 一\n",
    "beta/en/01-one.md": "# One\n",
  })
  const { vault, series } = readSeries(root)
  const { file, conflicts } = new ObsidianPreamble(series).write(vault)
  const text = fs.readFileSync(file, "utf8")
  assert.match(text, /^% Generated by `npm run preamble`/)
  assert.match(text, /\\renewcommand\{\\R\}\{\\mathbb\{R\}\}/)
  assert.match(text, /\\renewcommand\{\\E\}\{\\mathbb\{E\}\}/)
  assert.doesNotMatch(text, /mathbf/)
  assert.deepEqual(conflicts, ["\\R differs between alpha and beta; the preview uses alpha's"])
})
